// ignore_for_file: non_constant_identifier_names

List<String> keralaDistricts = [
  'District',
  'Thiruvananthapuram',
  'Kollam',
  'Pathanamthitta',
  'Alappuzha',
  'Kottayam',
  'Idukki',
  'Ernakulam',
  'Thrissur',
  'Palakkad',
  'Malappuram',
  'Kozhikode',
  'Wayanad',
  'Kannur',
  'Kasaragod',
];
List<String> AndhraPradeshDistricts = [
  'District',
  'Anantapur',
  'Chittoor',
  'East Godavari',
  'Guntur',
  'Krishna',
  'Kurnool',
  'Nellore',
  'Prakasam',
  'Srikakulam',
  'Visakhapatnam',
  'Vizianagaram',
  'West Godavari',
  'YSR Kadapa'
];
List<String> ArunachalPradeshDistricts = [
  'District',
  'Tawang',
  'West Kameng',
  'East Kameng',
  'Papum Pare',
  'Kurung Kumey',
  'Kra Daadi',
  'Lower Subansiri',
  'Upper Subansiri',
  'West Siang',
  'East Siang',
  'Siang',
  'Upper Siang',
  'Lower Siang',
  'Lower Dibang Valley',
  'Dibang Valley',
  'Anjaw',
  'Lohit',
  'Namsai',
  'Changlang',
  'Tirap',
  'Longding'
];
List<String> AssamDistricts = [
  'District',
  'Baksa',
  'Barpeta',
  'Biswanath',
  'Bongaigaon',
  'Cachar',
  'Charaideo',
  'Chirang',
  'Darrang',
  'Dhemaji',
  'Dhubri',
  'Dibrugarh',
  'Dima Hasao',
  'Goalpara',
  'Golaghat',
  'Hailakandi',
  'Hojai',
  'Jorhat',
  'Kamrup',
  'Kamrup Metropolitan',
  'Karbi Anglong',
  'Karimganj',
  'Kokrajhar',
  'Lakhimpur',
  'Majuli',
  'Morigaon',
  'Nagaon',
  'Nalbari',
  'Sivasagar',
  'Sonitpur',
  'South Salmara-Mankachar',
  'Tinsukia',
  'Udalguri',
  'West Karbi Anglong'
];
List<String> BiharDistricts = [
  'District',
  'Araria',
  'Arwal',
  'Aurangabad',
  'Banka',
  'Begusarai',
  'Bhagalpur',
  'Bhojpur',
  'Buxar',
  'Darbhanga',
  'East Champaran',
  'Gaya',
  'Gopalganj',
  'Jamui',
  'Jehanabad',
  'Kaimur',
  'Katihar',
  'Khagaria',
  'Kishanganj',
  'Lakhisarai',
  'Madhepura',
  'Madhubani',
  'Munger',
  'Muzaffarpur',
  'Nalanda',
  'Nawada',
  'Patna',
  'Purnia',
  'Rohtas',
  'Saharsa',
  'Samastipur',
  'Saran',
  'Sheikhpura',
  'Sheohar',
  'Sitamarhi',
  'Siwan',
  'Supaul',
  'Vaishali',
  'West Champaran'
];
List<String> ChhattisgarhDistricts = [
  'District',
  'Balod',
  'Baloda Bazar',
  'Balrampur',
  'Bastar',
  'Bemetara',
  'Bijapur',
  'Bilaspur',
  'Dantewada',
  'Dhamtari',
  'Durg',
  'Gariaband',
  'Janjgir-Champa',
  'Jashpur',
  'Kabirdham',
  'Kanker',
  'Kondagaon',
  'Korba',
  'Koriya',
  'Mahasamund',
  'Mungeli',
  'Narayanpur',
  'Raigarh',
  'Raipur',
  'Rajnandgaon',
  'Sukma',
  'Surajpur',
  'Surguja'
];
List<String> GoaDistricts = ['District', 'North Goa', 'South Goa'];
List<String> GujaratDistricts = [
  'District',
  'Ahmedabad',
  'Amreli',
  'Anand',
  'Aravalli',
  'Banaskantha',
  'Bharuch',
  'Bhavnagar',
  'Botad',
  'Chhota Udaipur',
  'Dahod',
  'Dang',
  'Devbhoomi Dwarka',
  'Gandhinagar',
  'Gir Somnath',
  'Jamnagar',
  'Junagadh',
  'Kheda',
  'Kutch',
  'Mahisagar',
  'Mehsana',
  'Morbi',
  'Narmada',
  'Navsari',
  'Panchmahal',
  'Patan',
  'Porbandar',
  'Rajkot',
  'Sabarkantha',
  'Surat',
  'Surendranagar',
  'Tapi',
  'Vadodara',
  'Valsad'
];
List<String> HaryanaDistricts = [
  'District',
  'Ambala',
  'Bhiwani',
  'Charkhi Dadri',
  'Faridabad',
  'Fatehabad',
  'Gurugram',
  'Hisar',
  'Jhajjar',
  'Jind',
  'Kaithal',
  'Karnal',
  'Kurukshetra',
  'Mahendragarh',
  'Nuh',
  'Palwal',
  'Panchkula',
  'Panipat',
  'Rewari',
  'Rohtak',
  'Sirsa',
  'Sonipat',
  'Yamunanagar'
];
List<String> HimachalPradeshDistricts = [
  'District',
  'Bilaspur',
  'Chamba',
  'Hamirpur',
  'Kangra',
  'Kinnaur',
  'Kullu',
  'Lahaul and Spiti',
  'Mandi',
  'Shimla',
  'Sirmaur',
  'Solan',
  'Una'
];
List<String> JharkhandDistricts = [
  'District',
  'Bokaro',
  'Chatra',
  'Deoghar',
  'Dhanbad',
  'Dumka',
  'East Singhbhum',
  'Garhwa',
  'Giridih',
  'Godda',
  'Gumla',
  'Hazaribagh',
  'Jamtara',
  'Khunti',
  'Koderma',
  'Latehar',
  'Lohardaga',
  'Pakur',
  'Palamu',
  'Ramgarh',
  'Ranchi',
  'Sahibganj',
  'Seraikela-Kharsawan',
  'Simdega',
  'West Singhbhum'
];
List<String> KarnatakaDistricts = [
  'District',
  'Bagalkot',
  'Ballari (Bellary)',
  'Belagavi (Belgaum)',
  'Bengaluru (Bangalore) Rural',
  'Bengaluru (Bangalore) Urban',
  'Bidar',
  'Chamarajanagar',
  'Chikballapur',
  'Chikkamagaluru (Chikmagalur)',
  'Chitradurga',
  'Dakshina Kannada',
  'Davangere',
  'Dharwad',
  'Gadag',
  'Hassan',
  'Haveri',
  'Kalaburagi (Gulbarga)',
  'Kodagu',
  'Kolar',
  'Koppal',
  'Mandya',
  'Mysuru (Mysore)',
  'Raichur',
  'Ramanagara',
  'Shivamogga (Shimoga)',
  'Tumakuru (Tumkur)',
  'Udupi',
  'Uttara Kannada (Karwar)',
  'Vijayapura (Bijapur)',
  'Yadgir'
];
List<String> KeralaDistricts = [
  'District',
  'Thiruvananthapuram',
  'Kollam',
  'Pathanamthitta',
  'Alappuzha',
  'Kottayam',
  'Idukki',
  'Ernakulam',
  'Thrissur',
  'Palakkad',
  'Malappuram',
  'Kozhikode',
  'Wayanad',
  'Kannur',
  'Kasaragod'
];
List<String> MadhyaPradeshDistricts = [
  'District',
  'Bhopal',
  'Indore',
  'Jabalpur',
  'Gwalior',
  'Ujjain',
  'Sagar',
  'Ratlam',
  'Satna',
  'Dewas',
  'Guna',
  'Sehore',
  'Morena',
  'Khargone',
  'Singrauli',
  'Burhanpur',
  'Khandwa',
  'Bhind',
  'Chhindwara',
  'Hoshangabad',
  'Vidisha',
  'Damoh',
  'Mandsaur',
  'Raisen',
  'Rewa',
  'Balaghat',
  'Panna',
  'Shivpuri',
  'Ashoknagar'
];
List<String> MaharashtraDistricts = [
  'District',
  'Ahmednagar',
  'Akola',
  'Amravati',
  'Aurangabad',
  'Beed',
  'Bhandara',
  'Buldhana',
  'Chandrapur',
  'Dhule',
  'Gadchiroli',
  'Gondia',
  'Hingoli',
  'Jalgaon',
  'Jalna',
  'Kolhapur',
  'Latur',
  'Mumbai City',
  'Mumbai Suburban',
  'Nagpur',
  'Nanded',
  'Nandurbar',
  'Nashik',
  'Osmanabad',
  'Palghar',
  'Parbhani',
  'Pune',
  'Raigad',
  'Ratnagiri',
  'Sangli',
  'Satara',
  'Sindhudurg',
  'Solapur',
  'Thane',
  'Wardha',
  'Washim',
  'Yavatmal'
];
List<String> ManipurDistricts = [
  'District',
  'Bishnupur',
  'Chandel',
  'Churachandpur',
  'Imphal East',
  'Imphal West',
  'Jiribam',
  'Kakching',
  'Kamjong',
  'Kangpokpi',
  'Noney',
  'Pherzawl',
  'Senapati',
  'Tamenglong',
  'Tengnoupal',
  'Thoubal',
  'Ukhrul'
];
List<String> MeghalayaDistricts = [
  'District',
  'East Garo Hills',
  'East Jaintia Hills',
  'East Khasi Hills',
  'North Garo Hills',
  'Ribhoi',
  'South Garo Hills',
  'South West Garo Hills',
  'South West Khasi Hills',
  'West Garo Hills',
  'West Jaintia Hills',
  'West Khasi Hills'
];
List<String> MizoramDistricts = [
  'District',
  'Aizawl',
  'Champhai',
  'Kolasib',
  'Lawngtlai',
  'Lunglei',
  'Mamit',
  'Saiha',
  'Serchhip'
];
List<String> NagalandDistricts = [
  'District',
  'Dimapur',
  'Kiphire',
  'Kohima',
  'Longleng',
  'Mokokchung',
  'Mon',
  'Peren',
  'Phek',
  'Tuensang',
  'Wokha',
  'Zunheboto',
];
List<String> OdishaDistricts = [
  'District',
  'Angul',
  'Balangir',
  'Balasore',
  'Bargarh',
  'Bhadrak',
  'Boudh',
  'Cuttack',
  'Deogarh',
  'Dhenkanal',
  'Gajapati',
  'Ganjam',
  'Jagatsinghpur',
  'Jajpur',
  'Jharsuguda',
  'Kalahandi',
  'Kandhamal',
  'Kendrapara',
  'Kendujhar',
  'Khurda',
  'Koraput',
  'Malkangiri',
  'Mayurbhanj',
  'Nabarangpur',
  'Nayagarh',
  'Nuapada',
  'Puri',
  'Rayagada',
  'Sambalpur',
  'Subarnapur',
  'Sundargarh',
];
List<String> PunjabDistricts = [
  'District',
  'Amritsar',
  'Barnala',
  'Bathinda',
  'Faridkot',
  'Fatehgarh Sahib',
  'Fazilka',
  'Ferozepur',
  'Gurdaspur',
  'Hoshiarpur',
  'Jalandhar',
  'Kapurthala',
  'Ludhiana',
  'Mansa',
  'Moga',
  'Pathankot',
  'Patiala',
  'Rupnagar',
  'Sahibzada Ajit Singh Nagar',
  'Sangrur',
  'Shahid Bhagat Singh Nagar',
  'Sri Muktsar Sahib',
  'Tarn Taran',
];
List<String> RajasthanDistricts = [
  'District',
  'Ajmer',
  'Alwar',
  'Banswara',
  'Baran',
  'Barmer',
  'Bharatpur',
  'Bhilwara',
  'Bikaner',
  'Bundi',
  'Chittorgarh',
  'Churu',
  'Dausa',
  'Dholpur',
  'Dungarpur',
  'Hanumangarh',
  'Jaipur',
  'Jaisalmer',
  'Jalore',
  'Jhalawar',
  'Jhunjhunu',
  'Jodhpur',
  'Karauli',
  'Kota',
  'Nagaur',
  'Pali',
  'Pratapgarh',
  'Rajsamand',
  'Sawai Madhopur',
  'Sikar',
  'Sirohi',
  'Sri Ganganagar',
  'Tonk',
  'Udaipur',
];
List<String> SikkimDistricts = [
  'District',
  'East Sikkim',
  'North Sikkim',
  'South Sikkim',
  'West Sikkim',
];
List<String> TamilNaduDistricts = [
  'District',
  'Ariyalur',
  'Chengalpattu',
  'Chennai',
  'Coimbatore',
  'Cuddalore',
  'Dharmapuri',
  'Dindigul',
  'Erode',
  'Kallakurichi',
  'Kancheepuram',
  'Karur',
  'Krishnagiri',
  'Madurai',
  'Nagapattinam',
  'Namakkal',
  'Nilgiris',
  'Perambalur',
  'Pudukkottai',
  'Ramanathapuram',
  'Ranipet',
  'Salem',
  'Sivaganga',
  'Tenkasi',
  'Thanjavur',
  'Theni',
  'Thoothukudi',
  'Tiruchirappalli',
  'Tirunelveli',
  'Tirupathur',
  'Tiruppur',
  'Tiruvallur',
  'Tiruvannamalai',
  'Tiruvarur',
  'Vellore',
  'Viluppuram',
  'Virudhunagar',
];
List<String> TelanganaDistricts = [
  'District',
  'Adilabad',
  'Bhadradri Kothagudem',
  'Hyderabad',
  'Jagtial',
  'Jangaon',
  'Jayashankar Bhupalpally',
  'Jogulamba Gadwal',
  'Kamareddy',
  'Karimnagar',
  'Khammam',
  'Komaram Bheem',
  'Mahabubabad',
  'Mahabubnagar',
  'Mancherial',
  'Medak',
  'Medchal-Malkajgiri',
  'Nagarkurnool',
  'Nalgonda',
  'Nirmal',
  'Nizamabad',
  'Peddapalli',
  'Rajanna Sircilla',
  'Rangareddy',
  'Sangareddy',
  'Siddipet',
  'Suryapet',
  'Vikarabad',
  'Wanaparthy',
  'Warangal (Rural)',
  'Warangal (Urban)',
  'Yadadri Bhuvanagiri',
];
List<String> TripuraDistricts = [
  'District',
  'Dhalai',
  'Gomati',
  'Khowai',
  'North Tripura',
  'Sepahijala',
  'South Tripura',
  'Unakoti',
  'West Tripura',
];
List<String> UttarPradeshDistricts = [
  'District',
  'Agra',
  'Aligarh',
  'Allahabad',
  'Ambedkar Nagar',
  'Amethi',
  'Amroha',
  'Auraiya',
  'Azamgarh',
  'Baghpat',
  'Bahraich',
  'Ballia',
  'Balrampur',
  'Banda',
  'Barabanki',
  'Bareilly',
  'Basti',
  'Bijnor',
  'Budaun',
  'Bulandshahr',
  'Chandauli',
  'Chitrakoot',
  'Deoria',
  'Etah',
  'Etawah',
  'Faizabad',
  'Farrukhabad',
  'Fatehpur',
  'Firozabad',
  'Gautam Buddha Nagar',
  'Ghaziabad',
  'Ghazipur',
  'Gonda',
  'Gorakhpur',
  'Hamirpur',
  'Hapur',
  'Hardoi',
  'Hathras',
  'Jalaun',
  'Jaunpur',
  'Jhansi',
  'Kannauj',
  'Kanpur Dehat',
  'Kanpur Nagar',
  'Kasganj',
  'Kaushambi',
  'Kushinagar',
  'Lakhimpur Kheri',
  'Lalitpur',
  'Lucknow',
  'Maharajganj',
  'Mahoba',
  'Mainpuri',
  'Mathura',
  'Mau',
  'Meerut',
  'Mirzapur',
  'Moradabad',
  'Muzaffarnagar',
  'Pilibhit',
  'Pratapgarh',
  'Rae Bareli',
  'Rampur',
  'Saharanpur',
  'Sambhal',
  'Sant Kabir Nagar',
  'Shahjahanpur',
  'Shamli',
  'Shrawasti',
  'Siddharthnagar',
  'Sitapur',
  'Sonbhadra',
  'Sultanpur',
  'Unnao',
  'Varanasi',
];
List<String> UttarakhandDistricts = [
  'District',
  'Almora',
  'Bageshwar',
  'Chamoli',
  'Champawat',
  'Dehradun',
  'Haridwar',
  'Nainital',
  'Pauri Garhwal',
  'Pithoragarh',
  'Rudraprayag',
  'Tehri Garhwal',
  'Udham Singh Nagar',
  'Uttarkashi',
];
List<String> WestBengalDistricts = [
  'District',
  'Alipurduar',
  'Bankura',
  'Birbhum',
  'Cooch Behar',
  'Dakshin Dinajpur',
  'Darjeeling',
  'Hooghly',
  'Howrah',
  'Jalpaiguri',
  'Jhargram',
  'Kalimpong',
  'Kolkata',
  'Malda',
  'Murshidabad',
  'Nadia',
  'North 24 Parganas',
  'Paschim Bardhaman',
  'Paschim Medinipur',
  'Purba Bardhaman',
  'Purba Medinipur',
  'Purulia',
  'South 24 Parganas',
  'Uttar Dinajpur',
];
List<String> AndamanNicobarDistricts = [
  'District',
  'Nicobar',
  'North and Middle Andaman',
  'South Andaman',
];
List<String> ChandigarhDistricts = [
  'District',
  'Chandigarh',
];
List<String> LakshadweepDistricts = [
  'District',
  'Lakshadweep',
];
List<String> DelhiDistricts = [
  'District',
  'Central Delhi',
  'East Delhi',
  'New Delhi',
  'North Delhi',
  'North East Delhi',
  'North West Delhi',
  'Shahdara',
  'South Delhi',
  'South East Delhi',
  'South West Delhi',
  'West Delhi',
];
List<String> PuducherryDistricts = [
  'District',
  'Karaikal',
  'Mahe',
  'Puducherry',
  'Yanam',
];
